# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1253, 981)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(180, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.loadLogsButton = QtWidgets.QPushButton(self.groupBox_3)
        self.loadLogsButton.setGeometry(QtCore.QRect(30, 170, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadLogsButton.setFont(font)
        self.loadLogsButton.setObjectName("loadLogsButton")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 84, 15))
        self.label_2.setObjectName("label_2")
        self.coordsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.coordsLabel.setGeometry(QtCore.QRect(100, 30, 91, 16))
        self.coordsLabel.setObjectName("coordsLabel")
        self.saveInterpolatedLogsButton = QtWidgets.QPushButton(self.groupBox_3)
        self.saveInterpolatedLogsButton.setEnabled(False)
        self.saveInterpolatedLogsButton.setGeometry(QtCore.QRect(10, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.saveInterpolatedLogsButton.setFont(font)
        self.saveInterpolatedLogsButton.setAutoRepeat(False)
        self.saveInterpolatedLogsButton.setObjectName("saveInterpolatedLogsButton")
        self.gridLayout.addWidget(self.groupBox_3, 2, 5, 1, 2)
        self.drawBox = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drawBox.sizePolicy().hasHeightForWidth())
        self.drawBox.setSizePolicy(sizePolicy)
        self.drawBox.setMaximumSize(QtCore.QSize(16777215, 7080))
        self.drawBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.drawBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drawBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.drawBox.setLineWidth(1)
        self.drawBox.setMidLineWidth(0)
        self.drawBox.setObjectName("drawBox")
        self.gridLayout.addWidget(self.drawBox, 0, 1, 1, 6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.invertAxisButton = QtWidgets.QPushButton(self.groupBox_2)
        self.invertAxisButton.setGeometry(QtCore.QRect(8, 30, 81, 23))
        self.invertAxisButton.setObjectName("invertAxisButton")
        self.increaseZoomButton = QtWidgets.QPushButton(self.groupBox_2)
        self.increaseZoomButton.setGeometry(QtCore.QRect(60, 60, 30, 27))
        self.increaseZoomButton.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.increaseZoomButton.setFont(font)
        self.increaseZoomButton.setObjectName("increaseZoomButton")
        self.zoomLabel = QtWidgets.QLabel(self.groupBox_2)
        self.zoomLabel.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.zoomLabel.setObjectName("zoomLabel")
        self.decreaseZoomButton = QtWidgets.QPushButton(self.groupBox_2)
        self.decreaseZoomButton.setGeometry(QtCore.QRect(10, 60, 30, 27))
        self.decreaseZoomButton.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decreaseZoomButton.setFont(font)
        self.decreaseZoomButton.setObjectName("decreaseZoomButton")
        self.gridLayout.addWidget(self.groupBox_2, 2, 3, 1, 1)
        self.radiosBox = QtWidgets.QScrollArea(self.centralwidget)
        self.radiosBox.setMinimumSize(QtCore.QSize(0, 0))
        self.radiosBox.setMaximumSize(QtCore.QSize(16777215, 250))
        self.radiosBox.setLineWidth(3)
        self.radiosBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.radiosBox.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.radiosBox.setWidgetResizable(False)
        self.radiosBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.radiosBox.setObjectName("radiosBox")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 915, 1200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(0, -2, 911, 1201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.reproduccionBox = QtWidgets.QGroupBox(self.groupBox)
        self.reproduccionBox.setEnabled(False)
        self.reproduccionBox.setGeometry(QtCore.QRect(0, 0, 911, 80))
        self.reproduccionBox.setObjectName("reproduccionBox")
        self.playStopButton = QtWidgets.QPushButton(self.reproduccionBox)
        self.playStopButton.setGeometry(QtCore.QRect(310, 30, 41, 41))
        self.playStopButton.setCheckable(True)
        self.playStopButton.setFlat(False)
        self.playStopButton.setObjectName("playStopButton")
        self.speedSecBox = QtWidgets.QSpinBox(self.reproduccionBox)
        self.speedSecBox.setGeometry(QtCore.QRect(90, 50, 121, 31))
        self.speedSecBox.setMaximum(59)
        self.speedSecBox.setProperty("value", 1)
        self.speedSecBox.setObjectName("speedSecBox")
        self.speedMinBox = QtWidgets.QSpinBox(self.reproduccionBox)
        self.speedMinBox.setGeometry(QtCore.QRect(90, 20, 121, 31))
        self.speedMinBox.setMaximum(7200)
        self.speedMinBox.setObjectName("speedMinBox")
        self.label = QtWidgets.QLabel(self.reproduccionBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.reproduccionBox)
        self.label_3.setGeometry(QtCore.QRect(230, 40, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.reproduccionBox)
        self.label_4.setGeometry(QtCore.QRect(380, 20, 91, 20))
        self.label_4.setObjectName("label_4")
        self.playPositionSlider = QtWidgets.QSlider(self.reproduccionBox)
        self.playPositionSlider.setGeometry(QtCore.QRect(380, 40, 521, 20))
        self.playPositionSlider.setMaximum(500)
        self.playPositionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playPositionSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.playPositionSlider.setTickInterval(60)
        self.playPositionSlider.setObjectName("playPositionSlider")
        self.actualPlayLabel = QtWidgets.QLabel(self.reproduccionBox)
        self.actualPlayLabel.setGeometry(QtCore.QRect(500, 20, 191, 20))
        self.actualPlayLabel.setObjectName("actualPlayLabel")
        self.minPlayLabel = QtWidgets.QLabel(self.reproduccionBox)
        self.minPlayLabel.setGeometry(QtCore.QRect(360, 60, 191, 20))
        self.minPlayLabel.setObjectName("minPlayLabel")
        self.maxPlayLabel = QtWidgets.QLabel(self.reproduccionBox)
        self.maxPlayLabel.setGeometry(QtCore.QRect(770, 60, 141, 20))
        self.maxPlayLabel.setObjectName("maxPlayLabel")
        self.speedTickBox = QtWidgets.QSpinBox(self.reproduccionBox)
        self.speedTickBox.setGeometry(QtCore.QRect(0, 50, 91, 31))
        self.speedTickBox.setMinimum(1)
        self.speedTickBox.setMaximum(20)
        self.speedTickBox.setProperty("value", 1)
        self.speedTickBox.setObjectName("speedTickBox")
        self.enableReproduccionBoxCheckBox = QtWidgets.QCheckBox(self.reproduccionBox)
        self.enableReproduccionBoxCheckBox.setGeometry(QtCore.QRect(90, 0, 31, 21))
        self.enableReproduccionBoxCheckBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.enableReproduccionBoxCheckBox.setAutoFillBackground(False)
        self.enableReproduccionBoxCheckBox.setText("")
        self.enableReproduccionBoxCheckBox.setObjectName("enableReproduccionBoxCheckBox")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(0, 90, 881, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.radiosBox.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.radiosBox, 2, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1253, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Control"))
        self.loadLogsButton.setText(_translate("MainWindow", "Load Logs"))
        self.label_2.setText(_translate("MainWindow", "Coordenadas:"))
        self.coordsLabel.setText(_translate("MainWindow", "[x,y,z]"))
        self.saveInterpolatedLogsButton.setText(_translate("MainWindow", "Save Interpolated Logs"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Zoom"))
        self.invertAxisButton.setText(_translate("MainWindow", "Invert   Y"))
        self.increaseZoomButton.setText(_translate("MainWindow", "+"))
        self.zoomLabel.setText(_translate("MainWindow", "----------"))
        self.decreaseZoomButton.setText(_translate("MainWindow", "-"))
        self.reproduccionBox.setTitle(_translate("MainWindow", "Reproduccion"))
        self.playStopButton.setText(_translate("MainWindow", ">"))
        self.speedSecBox.setSuffix(_translate("MainWindow", " seg / tick"))
        self.speedMinBox.setSuffix(_translate("MainWindow", " min / tick"))
        self.label.setText(_translate("MainWindow", "Velocidad:"))
        self.label_3.setText(_translate("MainWindow", "Play/Pause"))
        self.label_4.setText(_translate("MainWindow", "Posicion actual"))
        self.actualPlayLabel.setText(_translate("MainWindow", "----/--/--  --:--:--"))
        self.minPlayLabel.setText(_translate("MainWindow", "----/--/--  --:--:--"))
        self.maxPlayLabel.setText(_translate("MainWindow", "----/--/--  --:--:--"))
        self.speedTickBox.setSuffix(_translate("MainWindow", " tick / s"))

